### ISSUE TITLE
[3차 스프린트 - Webtoon] 컨트롤러 테스트 작성 및 RestDocs 문서화

### ISSUE THREAD

**Issue by na-yk** [Wonna-Park-Toon/server#30]
### 🟩 Task
- [ ] `AdminWebtoonController` 테스트 작성
- [x] `DefaultWebtoonController` 테스트 작성
- [x] `GuestWebtoonController` 테스트 작성

**Comment by na-yk** [comment]
User 통합 테스트 진행 후 재개
- [x] AdminWebtoonController 웹툰 상세정보 수정 API given 로직 추가
- [ ] AdminWebtoonController 웹툰 삭제 API 작성
