### ISSUE TITLE
[1차 스프린트 - Episode] Controller Test 작성 및 문서화 환경 구성 

### ISSUE THREAD

**Issue by smartandhandsome** [Wonna-Park-Toon/server#8]
### 🟩 Task
- [x] EpisodeController 인가 처리하는 것 작성
- [x] EpisodeController Test 작성
- [x] Swagger 환경 구성 
- [x] Rest Docs 환경 구성
